---
- name: Genera llave ssh, crea usuario nuevo y añade la llave creada (publica) a cada host especificado.
  hosts: all
  tasks:
    #- name: Generar llave SSH
    #  openssh_keypair:
    #    path: /keys/app
    #    size: 2048  
    - name: Crear usuario app
      user:
        name: app
        password: app
        home: /home/app
    - name: Assert .ssh directory
      file:
        dest: /home/app/.ssh
        state: directory
        owner: app
        mode: '0700'
    - name: Instalar llave SSH publica
      copy:
        src: keys/app.pub
        dest: /home/app/.ssh/app.pub
        owner: app
        mode: '0600'
    - name: Instalar llave SSH
      authorized_key:
        user: app
        state: present
        # Con este comando le estamos indicando que le pase la llave que se encuentra en el fichero app.pub
        key: "{{ lookup('file', 'keys/app.pub') }}"

    